param(
  [int]$Days = 30,
  [int]$Width = 1920,
  [int]$Height = 1080,
  [string]$IndexUrl = 'https://bing.wdbyte.com/zh-cn/'
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root 'assets\pictures'
New-Item -ItemType Directory -Path $outDir -Force | Out-Null
$tmpDir = Join-Path $env:TEMP ('bing_' + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $tmpDir -Force | Out-Null

Write-Host "Fetching index: $IndexUrl"
$htmlPath = Join-Path $tmpDir 'index.html'
curl.exe -L -s -A 'Mozilla/5.0' -o $htmlPath $IndexUrl
if (-not (Test-Path $htmlPath)) { throw 'Failed to fetch index page.' }
$html = [System.IO.File]::ReadAllText($htmlPath, [System.Text.Encoding]::UTF8)

$rx = [regex]'th\?id=(OHR\.[A-Za-z0-9_\-]+?)_UHD\.jpg&rf=LaDigue_UHD\.jpg&pid=hp&w=3840&h=2160&rs=1&c=4"\s+class="bing-download"\s+data-region="[^"]*"\s+data-date="(\d{4}-\d{2}-\d{2})"\s+data-desc="([^"]*)"'

$entries = @()
$seen = @{}
foreach ($m in $rx.Matches($html)) {
  $date = $m.Groups[2].Value
  if ($seen.ContainsKey($date)) { continue }
  $seen[$date] = $true
  $entries += [pscustomobject]@{
    date = $date
    id   = $m.Groups[1].Value
    desc = [System.Net.WebUtility]::HtmlDecode($m.Groups[3].Value)
  }
}
$entries = $entries | Sort-Object date -Descending | Select-Object -First $Days
if ($entries.Count -eq 0) { throw 'No image entries parsed from index page.' }

$manifest = @()
$i = 0
foreach ($e in $entries) {
  $i++
  $outFile = Join-Path $outDir "$($e.date).jpg"
  $relFile = "assets/pictures/$($e.date).jpg"
  $url = "https://cn.bing.com/th?id=$($e.id)_UHD.jpg&pid=hp&w=$Width&h=$Height&rs=1&c=4"
  $ok = $false
  for ($try = 1; $try -le 3 -and -not $ok; $try++) {
    curl.exe -L -s -A 'Mozilla/5.0' -o $outFile $url
    if ((Test-Path $outFile) -and (Get-Item $outFile).Length -gt 20000) { $ok = $true }
    else { Start-Sleep -Milliseconds 500 }
  }
  if (-not $ok) { Write-Warning "download failed: $($e.date)"; continue }

  $manifest += [pscustomobject]@{
    file      = $relFile
    date      = $e.date
    title     = $e.desc
    copyright = $e.desc
  }
  Write-Host ("[{0}/{1}] {2}" -f $i, $entries.Count, $e.date)
}

Remove-Item -Recurse -Force $tmpDir -ErrorAction SilentlyContinue
if ($manifest.Count -eq 0) { throw 'Manifest is empty.' }

$json = $manifest | ConvertTo-Json -Depth 4
if ($manifest.Count -eq 1) { $json = "[$json]" }

$content = "window.Brain = window.Brain || {};" + "`r`n" +
  "// Auto-generated by tools/fetch-bing-pictures.ps1 - do not edit manually." + "`r`n" +
  "window.Brain.bingPictures = $json;" + "`r`n"

$manifestPath = Join-Path $root 'js\picture-manifest.js'
[System.IO.File]::WriteAllText($manifestPath, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Done: $($manifest.Count) images -> assets\pictures, manifest -> js\picture-manifest.js"
